BibliotecaESFE.UI/Controllers/AutoresController.cs
using BibliotecaESFE.EN;
using BibliotecaESFE.BL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;

namespace BibliotecaESFE.UI.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class AutoresController : Controller
    {
        AutoresBL autoresBL = new AutoresBL();
        // GET: AutoresController
        public async Task<IActionResult> Index(Autores autores = null)
        {
            if (autores == null)
                autores = new Autores();
            if (autores.Top_Aux == 0)
                autores.Top_Aux = 10; // setear el número de resgistro a mostrar
            else if (autores.Top_Aux == -1)
                autores.Top_Aux = 0;

            var autoros = await autoresBL.SearchAsync(autores);
            ViewBag.Top = autores.Top_Aux;
            return View(autoros);
        }

        // GET: AutoresController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var autores = await autoresBL.GetByIdAsync(new Autores { Id = id });
            return View(autores);
        }

        // GET: AutoresController/Create
        public ActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: AutoresController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Autores autores)
        {
            try
            {
                int result = await autoresBL.CreateAsync(autores);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View(autores);
            }
        }

        // GET: AutoresController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var autores = await autoresBL.GetByIdAsync(new Autores { Id = id });
            return View(autores);
        }

        // POST: AutoresController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Autores autores )
        {
            try
            {
                int result = await autoresBL.UpdateAsync(autores);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(autores);
            }
        }

        // GET: AutoresController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var autores = await autoresBL.GetByIdAsync(new Autores { Id = id });
            return View(autores);
        }

        // POST: AutoresController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<IActionResult> Delete(int id, Autores autores)
        {
            try
            {
                int result = await autoresBL.DeleteAsync(autores);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }
    }
}

BibliotecaESFE.UI/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BibliotecaESFE.EN;
using BibliotecaESFE.BL;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using BibliotecaESFE.DAL;


namespace BibliotecaESFE.UI.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class LibrosController : Controller
    {
        AutoresBL autoresBL = new AutoresBL();
        EditorialesBL editorialesBL = new EditorialesBL();
        CategoriasBL categoriasBL = new CategoriasBL();
        LibrosBL librosBL = new LibrosBL();
        CalificacionesReseniasBL calificacionesReseniasBL = new CalificacionesReseniasBL();
        UsuarioBL usuarioBL = new UsuarioBL();
        // GET: LibrosController

        // GET: LibrosController
        public async Task<IActionResult> Index(string searchTitle = "", int top = 10)
        {
            // Si searchTitle no es nulo o vacío, filtra los libros por título.
            var librosFiltrados = await librosBL.SearchIncludeLibrosAsync(new Libros { Titulo = searchTitle, Top_Aux = top });

            // Cargar las listas relacionadas como antes.
            var autores = await autoresBL.GetAllAsync();
            var editoriales = await editorialesBL.GetAllAsync();
            var categorias = await categoriasBL.GetAllAsync();
            var calificacionesResenias = await calificacionesReseniasBL.GetAllAsync();
            var usuarios = await usuarioBL.GetAllAsync();

            // Pasar todo a ViewBag como antes.
            ViewBag.Top = top;
            ViewBag.Autores = autores;
            ViewBag.Editoriales = editoriales;
            ViewBag.Categorias = categorias;
            ViewBag.CalificacionesResenias = calificacionesResenias;
            ViewBag.Usuarios = usuarios;

            return View(librosFiltrados);
        }

        public async Task<IActionResult> IndexUs()
        {
            var libros = new Libros(); // Si necesitas inicializar con valores específicos
            var libro = await librosBL.SearchIncludeLibrosAsync(libros);

            var calificacionesResenias = await calificacionesReseniasBL.GetAllAsync(); // Importante para mostrar calificaciones

            ViewBag.CalificacionesResenias = calificacionesResenias; // Pasar las calificaciones a la vista

            return View(libro);
        }

       
        // GET: LibrosController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var libros = await librosBL.GetByIdAsync(new Libros { Id = id });
            libros.Autores = await autoresBL.GetByIdAsync(new Autores { Id = libros.AutorId });
            libros.Editoriales = await editorialesBL.GetByIdAsync(new Editoriales { Id = libros.EditorialId });
            libros.Categorias = await categoriasBL.GetByIdAsync(new Categorias { Id = libros.CategoriaId });
            return View(libros);
        }
        public async Task<IActionResult> Calificar(int id)
        {
            var libros = await librosBL.GetByIdAsync(new Libros { Id = id });
            var usuario = await usuarioBL.SearchAsync(new Usuarios { Login = User.Identity.Name, Top_Aux = 1 });
            var actualUser = usuario.FirstOrDefault();
            ViewBag.Usuario = actualUser;
            ViewBag.Libro = libros;
            ViewBag.Error = "";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Calificar(CalificacionesResenias calificacionesResenias)
        {
            try
            {
                calificacionesResenias.Id = 0;
                calificacionesResenias.FechaCalificacion = DateTime.Now;
                int result = await calificacionesReseniasBL.CreateAsync(calificacionesResenias);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                ViewBag.CalificacionesResenias = await calificacionesReseniasBL.GetAllAsync();
                return View(calificacionesResenias);
            }
        }
       

        // GET: LibrosController/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Autores = await autoresBL.GetAllAsync();
            ViewBag.Editoriales = await editorialesBL.GetAllAsync();
            ViewBag.Categorias = await categoriasBL.GetAllAsync();
            ViewBag.Error = "";
            return View();
        }



        // POST: LibrosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Libros libros, IFormFile imagen)
        {
            try
            {

                int result = await librosBL.CreateAsync(libros);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                ViewBag.Autores = await autoresBL.GetAllAsync();
                ViewBag.Editoriales = await editorialesBL.GetAllAsync();
                ViewBag.Categorias = await categoriasBL.GetAllAsync();
                return View(libros);
            }
        }

        // GET: LibrosController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var libros = await librosBL.GetByIdAsync(new Libros { Id = id });
            ViewBag.Autores = await autoresBL.GetAllAsync();
            ViewBag.Editoriales = await editorialesBL.GetAllAsync();
            ViewBag.Categorias = await categoriasBL.GetAllAsync();
            return View(libros);
        }

        // POST: LibrosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Libros libros)
        {
            try
            {
                int result = await librosBL.UpdateAsync(libros);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Autores = await autoresBL.GetAllAsync();
                ViewBag.Editoriales = await editorialesBL.GetAllAsync();
                ViewBag.Categorias = await categoriasBL.GetAllAsync();
                return View(libros);
            }
        }

        // GET: LibrosController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var libros = await librosBL.GetByIdAsync(new Libros { Id = id });
            libros.Autores = await autoresBL.GetByIdAsync(new Autores { Id = libros.AutorId });
            libros.Editoriales = await editorialesBL.GetByIdAsync(new Editoriales { Id = libros.EditorialId });
            libros.Categorias = await categoriasBL.GetByIdAsync(new Categorias { Id = libros.CategoriaId });
            return View(libros);
        }

        // POST: LibrosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Libros libros)
        {
            try
            {
                int result = await librosBL.DeleteAsync(libros);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var librosDb = await librosBL.GetByIdAsync(libros);
                if (librosDb == null)
                    librosDb = new Libros();
                if (librosDb.Id > 0)
                    librosDb.Autores = await autoresBL.GetByIdAsync(new Autores { Id = librosDb.AutorId });
                if (librosDb.Id > 0)
                    librosDb.Editoriales = await editorialesBL.GetByIdAsync(new Editoriales { Id = librosDb.EditorialId });
                if (librosDb.Id > 0)
                    librosDb.Categorias = await categoriasBL.GetByIdAsync(new Categorias { Id = librosDb.CategoriaId });

                return View(librosDb);
            }
        }
    }
}

BibliotecaESFE.UI/Controllers/RoleController.cs
using BibliotecaESFE.BL;
using BibliotecaESFE.EN;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BibliotecaESFE.UI.Controllers
{
   [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class RoleController : Controller
    {
        RoleBL roleBL = new RoleBL();

        // acción muestra el listado de registros
        public async Task<IActionResult> Index(Role role = null)
        {
            if (role == null)
                role = new Role();
            if (role.Top_Aux == 0)
                role.Top_Aux = 10; // setear el número de registros a mostrar
            else if (role.Top_Aux == -1)
                role.Top_Aux = 0;

            var roles = await roleBL.SearchAsync(role);
            ViewBag.Top = role.Top_Aux;

            return View(roles);
        }



        // acción que muestra los detalles de un registro
        public async Task<IActionResult> Details(int id)
        {
            var role = await roleBL.GetByIdAsync(new Role { Id = id });
            return View(role);
        }

        // acción que muestra el formulario para agregar un nuevo rol
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // acción que recibe los datos del formulario y los envía a la bd
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Role role)
        {
            try
            {
                int result = await roleBL.CreateAsync(role);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(role);
            }
        }

        // acción que muestra el formulario con los datos cargados para modificar
        public async Task<IActionResult> Edit(int id)
        {
            var role = await roleBL.GetByIdAsync(new Role { Id = id });
            ViewBag.Error = "";
            return View(role);
        }

        // acción que recibe los datos modificados y los envía a la bd
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Role role)
        {
            try
            {
                int result = await roleBL.UpdateAsync(role);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(role);
            }
        }

        // acción que muestra los datos para confirmar la eliminación
        public async Task<IActionResult> Delete(int id)
        {
            var role = await roleBL.GetByIdAsync(new Role { Id = id });
            ViewBag.Error = "";
            return View(role);
        }

        // acción que recibe la confirmación de eliminar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Role role)
        {
            try
            {
                int result = await roleBL.DeleteAsync(role);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(role);
            }
        }
    }
}

BibliotecaESFE.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BibliotecaESFE.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <!-- Inclusión de Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<!-- Inclusión de Tailwind CSS -->
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/BibliotecaESFE.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-KdajLW7gY16ntGbAm/BqT5HapxRHlNuhG3F46zLp7d7Je5c26fBJz/hRLjO/kqzjwz9WY3GqSMTiGjKXzZcixQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">




                <style>
                    .navbar-brand {
                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                        font-size: 24px;
                        font-weight: bold;
                        color: #333;
                        text-decoration: none;
                        position: relative;
                        transition: color 0.3s ease;
                    }

                        .navbar-brand::before {
                            content: '';
                            position: absolute;
                            bottom: 0;
                            left: 0;
                            width: 100%;
                            height: 2px;
                            background-color: #007bff;
                            transform: scaleX(0);
                            transition: transform 0.3s ease;
                        }

                        .navbar-brand:hover {
                            color: #007bff;
                        }

                            .navbar-brand:hover::before {
                                transform: scaleX(1);
                            }
                </style>

               

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Administrador")) // para identificar entre usuario y admin
                        {
                             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca ESFE</a>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservas" asp-action="IndexUs">Reservas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Autores" asp-action="Index">Autores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Editoriales" asp-action="Index">Editoriales</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Prestamos" asp-action="Index">Prestamos</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="ChangePassword">Cambiar clave</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Usuario")) // para identificar entre usuario y admin
                        {
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca ESFE</a>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservas" asp-action="Index">Reservas</a>
                            </li>
                         
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Editoriales" asp-action="IndexUs">Editoriales</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="IndexUs">Libros</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="IndexUs">Categorias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Encargado")) // para identificar entre usuario y admin
                        {
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca ESFE</a>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservas" asp-action="IndexUs">Reservas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Autores" asp-action="Index">Autores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Editoriales" asp-action="Index">Editoriales</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }
                   
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>



    </div>
    <footer class="footer">
        <div class="container">
            <p class="contact-info">
                <span class="contact-label">Developer Contact -</span>
                <a href="https://www.facebook.com/profile.php?id=100087871459133&mibextid=ZbWKwL" target="_blank">
                    <i class="fab fa-facebook"></i> Facebook
                </a> |
                <a href="https://www.instagram.com/winraraelexis?igsh=M2QwamN4aml0MW5j" target="_blank">
                    <i class="fab fa-instagram"></i> Instagram
                </a> |
                <a href="https://wa.me/76272675?text=Hola,%20me%20gustaría%20enviar%20un%20mensaje" target="_blank">
                    <i class="fab fa-whatsapp"></i> WhatsApp
                </a>
            </p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html> 